### ISSUE TITLE
practicas

### ISSUE THREAD

**Issue by grupohernandezalba** [PadillaJorge/PracticaGoogleMaps1#2]
Hola @PadillaJorge muy buen trabajo , me gusto la funcionalidad y el diseño.

![Captura de Pantalla 2020-03-01 a la(s) 12 44 33](https://user-images.githubusercontent.com/14998558/75631664-7ac50b80-5bba-11ea-805e-0c044df0ed59.png)

**Comment by PadillaJorge** [comment]
Gracias, profesor.
